# Setup
title:               Justin
tagline:             'Code Monkey'
description:         'I write code and sometimes it compiles.'
url:                 https://jqphu.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Justin Phu
  url:               https://jqphu.dev
  email:             justinqphu@gmail.com

# Gems
plugins:
  - jekyll-paginate

kramdown:
  parse_block_html: true

highlighter: rouge

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
